global:
  scrape_interval:     15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
    - targets: ['192.168.8.100:9090']

  - job_name: 'spring-actuator'

    metrics_path: '/actuator/prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['192.168.8.100:8084']
